default: &default
  adapter: postgresql
  encoding: unicode
  # For detailsra on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: changebot_development

test:
  <<: *default
  database: changebot_test